# R glmnet comparison script
# Reads data from /tmp/test_data_*.csv (generated by Python)
# and runs glmnet on the same data
#
# Usage: Rscript dev/tests/_remote_r_comparison.R

library(glmnet)

cat("=== R glmnet Comparison (same data as Python) ===\n\n")

# --- Test 1: Lasso ---
cat("--- Lasso (alpha=1) ---\n")
X <- as.matrix(read.csv("/tmp/test_data_X.csv", header=FALSE))
y <- read.csv("/tmp/test_data_y.csv", header=FALSE)[,1]

for (alpha_val in c(0.01, 0.1, 1.0)) {
  fit <- glmnet(X, y, alpha = 1, lambda = alpha_val, standardize = FALSE, intercept = FALSE)
  coef_r <- as.vector(coef(fit))[-1]  # remove intercept
  cat(sprintf("  alpha=%.2f: coef[1:5] = [%s]\n", alpha_val,
              paste(round(coef_r[1:5], 10), collapse=", ")))
  write.csv(data.frame(coef=coef_r), sprintf("/tmp/r_lasso_alpha%.2f.csv", alpha_val), row.names=FALSE)
}

# --- Test 2: Ridge ---
cat("\n--- Ridge (alpha=0) ---\n")
y_ridge <- read.csv("/tmp/test_data_y_ridge.csv", header=FALSE)[,1]

# statgpu uses alpha directly, R glmnet uses lambda = alpha * n
# So R's lambda = alpha * n to match statgpu's convention
for (alpha_val in c(0.001, 0.01, 0.1)) {
  fit <- glmnet(X, y_ridge, alpha = 0, lambda = alpha_val, standardize = FALSE, intercept = TRUE)
  coef_r <- as.vector(coef(fit))  # includes intercept
  cat(sprintf("  alpha=%.3f: intercept=%.10f, coef[1:5] = [%s]\n", alpha_val,
              coef_r[1],
              paste(round(coef_r[2:6], 10), collapse=", ")))
  write.csv(data.frame(coef=coef_r), sprintf("/tmp/r_ridge_alpha%.3f.csv", alpha_val), row.names=FALSE)
}

# --- Test 3: ElasticNet ---
cat("\n--- ElasticNet ---\n")

for (l1r in c(0.3, 0.5, 0.7)) {
  fit <- glmnet(X, y, alpha = l1r, lambda = 0.1, standardize = FALSE, intercept = FALSE)
  coef_r <- as.vector(coef(fit))[-1]
  cat(sprintf("  l1_ratio=%.1f: coef[1:5] = [%s]\n", l1r,
              paste(round(coef_r[1:5], 10), collapse=", ")))
  write.csv(data.frame(coef=coef_r), sprintf("/tmp/r_elasticnet_l1r%.1f.csv", l1r), row.names=FALSE)
}

# --- Test 4: Logistic Lasso ---
cat("\n--- Logistic Lasso ---\n")
y_log <- read.csv("/tmp/test_data_y_logistic.csv", header=FALSE)[,1]

fit <- glmnet(X, y_log, family = "binomial", alpha = 1, lambda = 0.05,
              standardize = FALSE, intercept = TRUE)
coef_r <- as.vector(coef(fit))
cat(sprintf("  intercept=%.6f, coef[1:5] = [%s]\n",
            coef_r[1],
            paste(round(coef_r[2:6], 6), collapse=", ")))
write.csv(data.frame(coef=coef_r), "/tmp/r_logistic_l1.csv", row.names=FALSE)

# --- Test 5: Poisson Lasso ---
cat("\n--- Poisson Lasso ---\n")
y_poi <- read.csv("/tmp/test_data_y_poisson.csv", header=FALSE)[,1]

fit <- glmnet(X, y_poi, family = "poisson", alpha = 1, lambda = 0.01,
              standardize = FALSE, intercept = TRUE)
coef_r <- as.vector(coef(fit))
cat(sprintf("  intercept=%.6f, coef[1:5] = [%s]\n",
            coef_r[1],
            paste(round(coef_r[2:6], 6), collapse=", ")))
write.csv(data.frame(coef=coef_r), "/tmp/r_poisson_l1.csv", row.names=FALSE)

cat("\n=== All R comparisons complete ===\n")
