"""Solver convergence constants and thresholds."""

_SLACK_TOLERANCE = 1e-14
_DIVERGE_COEF_NORM_CAP = 100.0
_DIVERGE_OBJ_RATIO = 100.0
_DIVERGE_OBJ_ABS = 10.0
_BB_RESTART_DOT_TOL = 1e-14
_LIPSCHITZ_FLOOR = 1e-30
_LIPSCHITZ_SAFETY_LOGISTIC_CV = 2.0
