"""
statgpu: GPU-accelerated statistical methods

A sklearn-compatible library for statistical computing with GPU support.
"""

__version__ = "0.1.0"

from ._config import get_device, set_device, Device
from ._base import BaseEstimator
from .linear_model import (
    LinearRegression,
    LogisticRegression,
    LogisticRegressionCV,
    PoissonRegression,
    GammaRegression,
    InverseGaussianRegression,
    NegativeBinomialRegression,
    TweedieRegression,
    GeneralizedLinearModel,
    OrderedGeneralizedLinearModel,
    OrderedLogitRegression,
    OrderedProbitRegression,
    PenalizedGeneralizedLinearModel,
    PenalizedGLM_CV,
    PenalizedLinearRegression,
    PenalizedLogisticRegression,
    PenalizedPoissonRegression,
    ApproximateCVWarning,
    Ridge,
    RidgeCV,
    Lasso,
    LassoCV,
    ElasticNet,
    ElasticNetCV,
)
from .survival import CoxPH, CoxPHCV
from .panel import (
    PanelOLS,
    RandomEffects,
    PooledOLS,
    BetweenOLS,
    FirstDifferenceOLS,
    FamaMacBeth,
    hac_covariance,
)
from .backends import get_backend, NumpyBackend, CuPyBackend, TorchBackend
from .metrics import evaluate_binary_classification
from .feature_selection import (
    FixedXKnockoffSelector,
    KnockoffSelector,
    fixed_x_knockoff_filter,
    knockoff_filter,
    model_x_knockoff_filter,
)
from .inference import adjust_pvalues, combine_pvalues, multipletests
from .inference import bootstrap_statistic, permutation_test
from .anova import (
    f_oneway,
    f_twoway,
    f_welch,
    tukey_hsd,
    bonferroni,
    cohens_f,
    partial_eta_squared,
)
from .nonparametric import (
    BandwidthSelectionResult,
    KernelDensityEstimator,
    KDE,
    KDEBootstrapResult,
    KernelRegression,
    KernelRegressionRegressor,
    KernelRidge,
    KernelRidgeCV,
    fit_kde,
    fit_kernel_regression,
    kde_pdf,
    kde_confidence_interval,
    kernel_regression_predict,
    kde_bootstrap_confidence_interval,
    select_bandwidth,
    select_bandwidth_factor,
    bspline_basis,
    natural_cubic_spline_basis,
    SplineTransformer,
    cyclic_cubic_spline_basis,
    thin_plate_spline_basis,
    chi2_kernel,
    Nystroem,
    KernelPCA,
)
from .semiparametric import GAM
from .covariance import (
    EmpiricalCovariance,
    LedoitWolf,
    OAS,
    ShrunkCovariance,
    MinCovDet,
    GraphicalLasso,
    GraphicalLassoCV,
)
from .unsupervised import (
    PCA,
    IncrementalPCA,
    TruncatedSVD,
    KMeans,
    MiniBatchKMeans,
    DBSCAN,
    GaussianMixture,
    NMF,
    MiniBatchNMF,
    AgglomerativeClustering,
    UMAP,
    TSNE,
)

__all__ = [
    "get_device",
    "set_device",
    "Device",
    "BaseEstimator",
    "LinearRegression",
    "LogisticRegression",
    "LogisticRegressionCV",
    "PoissonRegression",
    "GammaRegression",
    "InverseGaussianRegression",
    "NegativeBinomialRegression",
    "TweedieRegression",
    "GeneralizedLinearModel",
    "OrderedGeneralizedLinearModel",
    "OrderedLogitRegression",
    "OrderedProbitRegression",
    "PenalizedGeneralizedLinearModel",
    "PenalizedGLM_CV",
    "PenalizedLinearRegression",
    "PenalizedLogisticRegression",
    "PenalizedPoissonRegression",
    "ApproximateCVWarning",
    "Ridge",
    "RidgeCV",
    "Lasso",
    "LassoCV",
    "ElasticNet",
    "ElasticNetCV",
    "CoxPH",
    "CoxPHCV",
    # Panel
    "PanelOLS",
    "RandomEffects",
    "PooledOLS",
    "BetweenOLS",
    "FirstDifferenceOLS",
    "FamaMacBeth",
    "hac_covariance",
    # Backends
    "get_backend",
    "NumpyBackend",
    "CuPyBackend",
    "TorchBackend",
    "evaluate_binary_classification",
    # Feature selection
    "FixedXKnockoffSelector",
    "KnockoffSelector",
    "fixed_x_knockoff_filter",
    "knockoff_filter",
    "model_x_knockoff_filter",
    # Inference
    "adjust_pvalues",
    "combine_pvalues",
    "multipletests",
    "bootstrap_statistic",
    "permutation_test",
    # ANOVA
    "f_oneway",
    "f_twoway",
    "f_welch",
    "tukey_hsd",
    "bonferroni",
    "cohens_f",
    "partial_eta_squared",
    # Nonparametric
    "BandwidthSelectionResult",
    "KernelDensityEstimator",
    "KDE",
    "KDEBootstrapResult",
    "KernelRegression",
    "KernelRegressionRegressor",
    "KernelRidge",
    "KernelRidgeCV",
    "fit_kde",
    "fit_kernel_regression",
    "kde_pdf",
    "kde_confidence_interval",
    "kernel_regression_predict",
    "kde_bootstrap_confidence_interval",
    "select_bandwidth",
    "select_bandwidth_factor",
    "bspline_basis",
    "natural_cubic_spline_basis",
    "SplineTransformer",
    "cyclic_cubic_spline_basis",
    "thin_plate_spline_basis",
    "chi2_kernel",
    "Nystroem",
    "KernelPCA",
    # Semiparametric
    "GAM",
    # Covariance
    "EmpiricalCovariance",
    "LedoitWolf",
    "OAS",
    "ShrunkCovariance",
    "MinCovDet",
    "GraphicalLasso",
    "GraphicalLassoCV",
    # Unsupervised
    "PCA",
    "IncrementalPCA",
    "TruncatedSVD",
    "KMeans",
    "MiniBatchKMeans",
    "DBSCAN",
    "GaussianMixture",
    "NMF",
    "MiniBatchNMF",
    "AgglomerativeClustering",
    "UMAP",
    "TSNE",
]
