from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise RuntimeError(f"anchor not found in {path}: {old[:180]!r}")
    p.write_text(text.replace(old, new, 1))


# English covariance documentation.
path = "docs/en/panel/covariance.md"
old = '''For extreme but finite score magnitudes, grouped score reductions selectively use a group-size working scale only where a same-sign partial sum could overflow, and positive/negative contributions are accumulated separately before the final cancellation. This protects the reduction itself without globally magnitude-normalizing unrelated safe groups. As with ordinary float64 linear algebra, this is not a promise to recover arbitrary tiny remainders after catastrophically ill-conditioned upstream cancellation.
'''
new = '''For extreme but finite score magnitudes, grouped score reductions selectively use a group-size working scale only where a same-sign partial sum could overflow, and positive/negative contributions are accumulated separately before the final cancellation. The shared residual-covariance path also delays tiny-design scale restoration until after the covariance reduction: working-SVD projection coordinates are rescaled only when their product with the largest residual could overflow, while the residual vector itself is never globally magnitude-normalized. One-way cluster scores and Driscoll-Kraay period scores are grouped before any Gram normalization, and the subsequent per-coordinate Gram scale is the minimum needed to keep the relevant product/reduction in range. This preserves representable small groups or periods beside much larger observations without perturbing ordinary or subnormal-design paths that are already safe. As with ordinary float64 linear algebra, this is not a promise to recover arbitrary tiny remainders after catastrophically ill-conditioned upstream cancellation.
'''
replace_once(path, old, new)
old = '''Two-way clustering combines the two one-way cluster covariances and subtracts the covariance for the paired cluster labels:
'''
new = '''Two-way clustering combines the two one-way cluster covariances and subtracts the covariance for the paired cluster labels. All three grouped-score components are formed before physical scale restoration. If one clustering dimension is nested in the other, statgpu recognizes equality of the induced partitions rather than equality of arbitrary integer codes and cancels the matching marginal/intersection component algebraically; otherwise the three components share one minimally scaled Gram space before inclusion-exclusion:
'''
replace_once(path, old, new)
old = '''Symmetric covariance combinations are evaluated with range-aware arithmetic: final symmetrization avoids overflowing a finite same-sign average, and two-way inclusion-exclusion subtracts a same-sign intersection component before a risky addition when possible. HAC/Driscoll-Kraay first form the symmetric lag average rather than an overflowing unweighted symmetric sum, then accumulate the lag sequence with a per-entry reduction-length working scale only where a transient partial sum could overflow. Safe and subnormal entries remain on their original scale. These reorderings are algebraically equivalent to the displayed definitions whenever the final float64 result is representable; as elsewhere, they do not claim higher-precision recovery from arbitrarily ill-conditioned cancellation.
'''
new = '''Symmetric covariance combinations are evaluated with range-aware arithmetic: final symmetrization avoids overflowing a finite same-sign average, and two-way inclusion-exclusion subtracts a same-sign intersection component before a risky addition when possible. HAC/Driscoll-Kraay normalize only score coordinates whose zero-lag Gram or weighted lag product would otherwise overflow, before those products are materialized; Driscoll-Kraay performs its period grouping first. They then form symmetric lag averages and accumulate the complete lag sequence with a per-entry reduction-length working scale only where a transient partial sum could overflow. Tiny-design and projection-product restore factors remain outside this cancellation space until the final covariance is formed. Safe coordinates, groups, periods, and subnormal-design paths therefore stay on their original working scale. These reorderings are algebraically equivalent to the displayed definitions whenever the final float64 result is representable; as elsewhere, they do not claim higher-precision recovery from arbitrarily ill-conditioned cancellation.
'''
replace_once(path, old, new)

# Chinese covariance documentation.
path = "docs/cn/panel/covariance.md"
old = '''对极端但仍有限的 score，grouped reduction 只在同号 partial sum 存在溢出风险的 group/coordinate 上使用 group-size working scale，并先分别累计正项与负项，再做最终 cancellation；不会因为某个危险 group 而对其他安全 group 做全局 magnitude normalization。和一般 float64 线性代数一样，这并不承诺在上游已经发生灾难性病态 cancellation 后恢复任意微小 remainder。
'''
new = '''对极端但仍有限的 score，grouped reduction 只在同号 partial sum 存在溢出风险的 group/coordinate 上使用 group-size working scale，并先分别累计正项与负项，再做最终 cancellation。shared residual-covariance 路径还会把 tiny-design scale 的恢复推迟到 covariance reduction 之后：working-SVD projection coordinate 只有在其与最大 residual 的乘积可能溢出时才做最小必要缩放，而 residual vector 本身不会被全局 magnitude normalization。one-way cluster score 与 Driscoll-Kraay period score 都先完成 grouping，再对 Gram product 使用刚好足以避免溢出的 per-coordinate working scale；已经安全的普通路径与 subnormal-design 路径不做额外 normalization，因此巨大 observation 旁边仍可表示的小 group/period contribution 不会被无关的全局尺度抹掉。和一般 float64 线性代数一样，这并不承诺在上游已经发生灾难性病态 cancellation 后恢复任意微小 remainder。
'''
replace_once(path, old, new)
old = '''双向 clustering 将两个 one-way cluster covariance 相加，再减去 paired cluster labels 对应的 covariance：
'''
new = '''双向 clustering 将两个 one-way cluster covariance 相加，再减去 paired cluster labels 对应的 covariance。三个 grouped-score component 都在恢复物理尺度之前形成；如果一个 clustering dimension 嵌套在另一个 dimension 中，statgpu 比较的是两者诱导的 partition 是否等价，而不是任意 integer code 是否逐元素相同，并在 working space 中代数消去相同的 marginal/intersection component。非嵌套情形则让三个 component 共用同一个最小 Gram working scale 后再做 inclusion-exclusion：
'''
replace_once(path, old, new)
old = '''对 symmetric covariance combination，statgpu 使用 range-aware arithmetic：最终 symmetrization 会避免有限同号平均值在相加阶段先溢出；two-way inclusion-exclusion 会在可能时先减去同号 intersection component。HAC/Driscoll-Kraay 会先形成 symmetric lag average，而不是先构造可能溢出的未加权 symmetric sum；随后对整个 lag sequence 只在某个 entry 的 transient partial sum 存在溢出风险时使用 per-entry reduction-length working scale，安全与 subnormal entry 保持原尺度。只要最终 float64 结果可表示，这些重排与上面的统计定义代数等价；与其他数值路径一样，并不宣称可以用更高精度恢复任意病态 cancellation。
'''
new = '''对 symmetric covariance combination，statgpu 使用 range-aware arithmetic：最终 symmetrization 会避免有限同号平均值在相加阶段先溢出；two-way inclusion-exclusion 会在可能时先减去同号 intersection component。HAC/Driscoll-Kraay 会在 zero-lag Gram 或 weighted lag product 真正 materialize 之前，只对存在乘积溢出风险的 score coordinate 做最小必要 normalization；Driscoll-Kraay 先完成 period grouping。之后再形成 symmetric lag average，并对完整 lag sequence 只在某个 entry 的 transient partial sum 存在溢出风险时使用 per-entry reduction-length working scale。tiny-design 与 projection-product 的 restore factor 一直保留在 cancellation space 之外，直到最终 covariance 才恢复，因此安全 coordinate、group、period 与 subnormal-design 路径保持原 working scale。只要最终 float64 结果可表示，这些重排与上面的统计定义代数等价；与其他数值路径一样，并不宣称可以用更高精度恢复任意病态 cancellation。
'''
replace_once(path, old, new)

# Root changelog.
path = "CHANGELOG.md"
old = '''- **Panel covariance extreme-scale arithmetic**: clustered score grouping selectively rescales only overflow-risk group/coordinate reductions and combines positive/negative contributions after safe accumulation; covariance symmetrization and two-way cluster inclusion-exclusion use range-aware algebraic reorderings. HAC/Driscoll-Kraay additionally use a per-entry reduction-length accumulator across the complete lag sequence, so a transient positive partial sum cannot become `Inf` before later finite negative lag contributions restore a representable covariance. The physical Stage-C validator exercises these primitives on both CuPy and Torch CUDA.
'''
new = '''- **Panel covariance extreme-scale arithmetic**: residual-based covariance now keeps tiny-design/projection restore factors outside observation-level cancellation. Working projection coordinates are scaled only when projection×residual would overflow; residual vectors are never globally magnitude-normalized. Cluster and Driscoll-Kraay grouping occurs before selective Gram scaling, preserving representable small groups/periods beside huge cancelling observations, while already-safe subnormal-design HC/cluster paths retain their previous precision. Two-way clustering combines grouped components before restoration and detects nested dimensions by partition equivalence rather than arbitrary code numbering. Covariance symmetrization and inclusion-exclusion remain range-aware, while HAC/Driscoll-Kraay protect both pre-Gram products and the complete lag-sequence accumulator from avoidable overflow. The physical Stage-C validator exercises pre-Gram cancellation, tiny-design grouping, mixed-dynamic-range cluster/DK, nested-code permutation, and the earlier extreme-scale cases on CuPy and Torch CUDA.
'''
replace_once(path, old, new)

# English public changelog.
path = "docs/en/changelog.md"
old = '''The latest numerical hardening unifies NumPy/CuPy/Torch Fama-MacBeth period dispatch under the same conservative Gram certificate and maintained SVD fallback. The certificate rejects non-finite Gram/RHS/solutions before they can preempt fallback; shared SVD least-squares uses inverse-singular-value factor ordering plus a safe uniform working scale for collectively subnormal full-rank designs. Fama-MacBeth coefficient averages and shared parameter-R² means use reduction-length scaling only when overflow is possible, avoiding extra magnitude-normalization loss without claiming arbitrary compensated cancellation recovery; coefficient-series covariance uses per-coordinate scales with symmetric restoration. Shared panel inference no longer imposes an absolute variance floor: exact-zero variance maps a zero coefficient to statistic 0 and a nonzero coefficient to signed infinity. Classical model F, pooling F, and Breusch-Pagan LM use overflow-safe centering and subnormal-safe backend normalization. Cluster grouping, covariance symmetrization, and two-way inclusion-exclusion now use range-aware arithmetic to avoid preventable intermediate overflow. HAC/Driscoll-Kraay also use a per-entry reduction-length accumulator across the full lag sequence, so an overflowing transient partial sum cannot erase a later cancellation when the final covariance remains representable. The maintained physical Stage-C runner includes the diagnostic-scale, zero-variance, covariance extreme-scale, and lag-accumulation branches for both CuPy and Torch CUDA.
'''
new = '''The latest numerical hardening unifies NumPy/CuPy/Torch Fama-MacBeth period dispatch under the same conservative Gram certificate and maintained SVD fallback. The certificate rejects non-finite Gram/RHS/solutions before they can preempt fallback; shared SVD least-squares uses inverse-singular-value factor ordering plus a safe uniform working scale for collectively subnormal full-rank designs. Fama-MacBeth coefficient averages and shared parameter-R² means use reduction-length scaling only when overflow is possible, avoiding extra magnitude-normalization loss without claiming arbitrary compensated cancellation recovery; coefficient-series covariance uses per-coordinate scales with symmetric restoration. Shared panel inference no longer imposes an absolute variance floor: exact-zero variance maps a zero coefficient to statistic 0 and a nonzero coefficient to signed infinity. Classical model F, pooling F, and Breusch-Pagan LM use overflow-safe centering and subnormal-safe backend normalization. Residual-based covariance now delays tiny-design/projection scale restoration until after cancellation: projection coordinates are scaled only when projection×residual would overflow, cluster and DK scores are grouped before selective Gram scaling, and residual vectors are never globally magnitude-normalized. This preserves small representable components beside huge cancelling observations without degrading already-safe subnormal-design precision. Two-way clustering recognizes nested partitions independently of arbitrary code numbering and cancels identical marginal/intersection components before restoration. Range-aware symmetrization/inclusion-exclusion plus HAC/DK pre-Gram and full-lag accumulators then prevent avoidable intermediate overflow. The maintained physical Stage-C runner includes diagnostic-scale, zero-variance, pre-Gram, tiny-design, mixed-range, nested-partition, covariance extreme-scale, and lag-accumulation branches for both CuPy and Torch CUDA.
'''
replace_once(path, old, new)

# Chinese public changelog.
path = "docs/cn/changelog.md"
old = '''最新的 numerical hardening 让 NumPy/CuPy/Torch 的 Fama-MacBeth period solve 统一经过同一 conservative Gram certificate 与 maintained SVD fallback。certificate 会在 fallback 前拒绝 non-finite Gram/RHS/solution；shared SVD least-squares 使用 inverse-singular-value factor ordering，并对整体 subnormal 但 full-rank 的 design 使用安全统一 working scale。Fama-MacBeth coefficient average 与 shared parameter-R² mean 只在存在溢出风险时使用 reduction-length scaling，以避免全局 magnitude normalization 额外造成的信息损失，但不宣称可以恢复任意病态 cancellation remainder；coefficient-series covariance 使用 per-coordinate scale 与 symmetric restoration。shared panel inference 不再施加绝对 variance floor：exact-zero variance 下，零 coefficient 的 statistic 为 0，非零 coefficient 为带符号无穷。Classical model F、pooling F 与 Breusch-Pagan LM 使用 overflow-safe centering 和 subnormal-safe backend normalization；cluster grouping、covariance symmetrization 与 two-way inclusion-exclusion 也改用 range-aware arithmetic，避免可表示有限结果因不必要的中间溢出而丢失。HAC/Driscoll-Kraay 进一步对完整 lag sequence 使用 per-entry reduction-length accumulator，避免 transient partial sum 先变成 `Inf` 后使后续本可恢复的 cancellation 失效。maintained physical Stage-C runner 已把 diagnostic-scale、zero-variance、covariance extreme-scale 与 lag-accumulation 分支加入 CuPy 与 Torch CUDA 验证。
'''
new = '''最新的 numerical hardening 让 NumPy/CuPy/Torch 的 Fama-MacBeth period solve 统一经过同一 conservative Gram certificate 与 maintained SVD fallback。certificate 会在 fallback 前拒绝 non-finite Gram/RHS/solution；shared SVD least-squares 使用 inverse-singular-value factor ordering，并对整体 subnormal 但 full-rank 的 design 使用安全统一 working scale。Fama-MacBeth coefficient average 与 shared parameter-R² mean 只在存在溢出风险时使用 reduction-length scaling，以避免全局 magnitude normalization 额外造成的信息损失，但不宣称可以恢复任意病态 cancellation remainder；coefficient-series covariance 使用 per-coordinate scale 与 symmetric restoration。shared panel inference 不再施加绝对 variance floor：exact-zero variance 下，零 coefficient 的 statistic 为 0，非零 coefficient 为带符号无穷。Classical model F、pooling F 与 Breusch-Pagan LM 使用 overflow-safe centering 和 subnormal-safe backend normalization。residual-based covariance 现在把 tiny-design/projection scale 的恢复推迟到 cancellation 之后：projection coordinate 只在 projection×residual 可能溢出时缩放，cluster 与 DK score 先 grouping 再做 selective Gram scaling，而且 residual vector 不会被全局 magnitude normalization，因此巨大 cancellation 旁边仍可表示的小 component 可以保留，同时已经安全的 subnormal-design 精度不被额外 normalization 破坏。two-way clustering 按 partition 等价而不是任意 code 编号识别 nested dimension，并在恢复尺度前代数消去相同 marginal/intersection component。range-aware symmetrization/inclusion-exclusion 与 HAC/DK 的 pre-Gram、full-lag accumulator 共同避免可恢复的中间溢出。maintained physical Stage-C runner 已把 diagnostic-scale、zero-variance、pre-Gram、tiny-design、mixed-range、nested-partition、covariance extreme-scale 与 lag-accumulation 分支加入 CuPy 与 Torch CUDA 验证。
'''
replace_once(path, old, new)
