from pathlib import Path

p = Path("statgpu/panel/_covariance.py")
text = p.read_text(encoding="utf-8")
old = '''def _cross_reduction_is_safe(left, right, xp) -> bool:\n    """Return whether ``left.T @ right`` has a conservative float64 range bound.\n\n    This is deliberately only a sufficient condition.  It is used to select a\n    cancellation-preserving two-way-cluster shortcut; if the bound is not met,\n    callers retain the existing scaled covariance path.\n    """\n    n_terms = max(1, int(left.shape[0]))\n    left_max = _to_float_scalar(xp.max(xp.abs(left)))\n    right_max = _to_float_scalar(xp.max(xp.abs(right)))\n    if not np.isfinite(left_max) or not np.isfinite(right_max):\n        return False\n    if left_max == 0.0 or right_max == 0.0:\n        return True\n    # Keep a factor-four range margin, matching the Gram working-scale policy.\n    per_term_limit = 0.25 * float(np.finfo(np.float64).max) / float(n_terms)\n    return bool(left_max <= per_term_limit / right_max)\n'''
new = '''def _cross_reduction_is_safe(left, right, xp) -> bool:\n    """Return whether ``left.T @ right`` has a conservative rowwise range bound.\n\n    Matrix-product terms pair values from the same observation.  Bounding the\n    product of unrelated column maxima can therefore reject a safe structural\n    cancellation (for example, a huge left score where the corresponding right\n    score is exactly zero).  Use per-row infinity norms instead.  This remains\n    only a sufficient condition: any uncertain case stays on the scaled\n    component path.\n    """\n    n_terms = max(1, int(left.shape[0]))\n    if _is_torch(xp):\n        left_row_max = xp.max(xp.abs(left), dim=1).values\n        right_row_max = xp.max(xp.abs(right), dim=1).values\n    else:\n        left_row_max = xp.max(xp.abs(left), axis=1)\n        right_row_max = xp.max(xp.abs(right), axis=1)\n\n    finite = xp.isfinite(left_row_max) & xp.isfinite(right_row_max)\n    large = xp.maximum(left_row_max, right_row_max)\n    small = xp.minimum(left_row_max, right_row_max)\n    one = xp.ones_like(large)\n    safe_large = xp.maximum(large, one)\n    per_term_limit = 0.25 * float(np.finfo(np.float64).max) / float(n_terms)\n    safe = finite & (small <= float(per_term_limit) / safe_large)\n    return bool(_to_float_scalar(xp.all(safe)))\n'''
if new in text:
    raise SystemExit(0)
if old not in text:
    raise RuntimeError("cross-reduction helper anchor not found")
p.write_text(text.replace(old, new, 1), encoding="utf-8")
