from pathlib import Path

p = Path("statgpu/panel/_covariance.py")
text = p.read_text(encoding="utf-8")
old = '''            component_sets = (components1, components2, components12)\n            if _component_row_reduction_needs_expansion(component_sets, xp):\n                component_sets = _retier_component_sets_for_safe_gram(\n                    component_sets, xp\n                )\n                components1, components2, components12 = component_sets\n'''
new = '''            component_sets = (components1, components2, components12)\n            needs_row_expansion = _component_row_reduction_needs_expansion(\n                component_sets, xp\n            )\n            if needs_row_expansion:\n                component_sets = _retier_component_sets_for_safe_gram(\n                    component_sets, xp\n                )\n                components1, components2, components12 = component_sets\n'''
if new not in text:
    if old not in text:
        raise RuntimeError("row-expansion predicate anchor not found")
    text = text.replace(old, new, 1)

old2 = '''            terms = []\n\n            def _append_scaled_row_term(term, coefficient):\n                for dyadic in _dyadic_float_terms(coefficient):\n                    terms.append(term * float(dyadic))\n\n            def _append_component_terms(components, correction, sign):\n                coefficient = float(sign) * float(correction)\n                for i, left in enumerate(components):\n                    for row in range(int(left.shape[0])):\n                        vector = left[row]\n                        outer = vector[:, None] * vector[None, :]\n                        _append_scaled_row_term(outer, coefficient)\n                    for right in components[:i]:\n                        for row in range(int(left.shape[0])):\n                            cross = left[row, :, None] * right[row, None, :]\n                            _append_scaled_row_term(cross + cross.T, coefficient)\n\n            # This branch is already the rare multi-tier precision fallback.\n            # Keep row products out of signed BLAS reductions and decompose float\n            # debias corrections into exact dyadic factors; then accumulate all\n            # estimator-level terms with two compensated error streams. Ordinary\n            # single-tier/vectorized covariance paths are unchanged.\n            _append_component_terms(work1, correction1, 1.0)\n            _append_component_terms(work2, correction2, 1.0)\n            _append_component_terms(work12, correction12, -1.0)\n            cov_work = _twofold_matrix_sum(terms, xp)\n'''
new2 = '''            terms = []\n\n            if needs_row_expansion:\n                def _append_scaled_row_term(term, coefficient):\n                    for dyadic in _dyadic_float_terms(coefficient):\n                        terms.append(term * float(dyadic))\n\n                def _append_component_terms(components, correction, sign):\n                    coefficient = float(sign) * float(correction)\n                    for i, left in enumerate(components):\n                        for row in range(int(left.shape[0])):\n                            vector = left[row]\n                            outer = vector[:, None] * vector[None, :]\n                            _append_scaled_row_term(outer, coefficient)\n                        for right in components[:i]:\n                            for row in range(int(left.shape[0])):\n                                cross = left[row, :, None] * right[row, None, :]\n                                _append_scaled_row_term(cross + cross.T, coefficient)\n\n                # Only the pathological cross-group dynamic-range branch uses\n                # row-level compensated accumulation.  Keep row products out of\n                # signed BLAS reductions and expand float debias corrections into\n                # exact dyadic factors before estimator-level cancellation.\n                _append_component_terms(work1, correction1, 1.0)\n                _append_component_terms(work2, correction2, 1.0)\n                _append_component_terms(work12, correction12, -1.0)\n                cov_work = _twofold_matrix_sum(terms, xp)\n            else:\n                def _append_vectorized_component_terms(components, correction, sign):\n                    coefficient = float(sign) * float(correction)\n                    for i, left in enumerate(components):\n                        terms.append(_symmetrize(left.T @ left) * coefficient)\n                        for right in components[:i]:\n                            cross = left.T @ right\n                            terms.append((cross + cross.T) * coefficient)\n\n                # Local grouped-score tiers do not by themselves require the\n                # row-level fallback.  If every cross-group component pair is\n                # certified safe, retain the vectorized BLAS/GPU expansion.\n                _append_vectorized_component_terms(work1, correction1, 1.0)\n                _append_vectorized_component_terms(work2, correction2, 1.0)\n                _append_vectorized_component_terms(work12, correction12, -1.0)\n                cov_work = _stable_matrix_expansion_sum(terms, xp)\n'''
if new2 not in text:
    if old2 not in text:
        raise RuntimeError("row-expansion implementation anchor not found")
    text = text.replace(old2, new2, 1)
p.write_text(text, encoding="utf-8")

p = Path("CHANGELOG.md")
text = p.read_text(encoding="utf-8")
old = "In the rare multi-tier nonnested precision fallback, grouped row outer products remain separate terms, float group-debias corrections are decomposed into exact power-of-two factors, and two compensated error streams preserve magnitude-tier/CGM/debias cancellation without changing ordinary vectorized paths."
new = "When a multi-tier nonnested case also fails the cross-group row-reduction safety certificate, grouped row outer products remain separate terms, float group-debias corrections are decomposed into exact power-of-two factors, and two compensated error streams preserve magnitude-tier/CGM/debias cancellation; Gram-safe multi-tier cases retain the vectorized component-matrix path."
if new not in text:
    if old not in text:
        raise RuntimeError("CHANGELOG precision-fallback anchor not found")
    text = text.replace(old, new, 1)
p.write_text(text, encoding="utf-8")
