"""Inference helper utilities shared across models."""

from ._distributions_backend import (
    BetaDistributionBase,
    BinomDistributionBase,
    CauchyDistributionBase,
    Chi2DistributionBase,
    ExponDistributionBase,
    FDistributionBase,
    GammaDistributionBase,
    LaplaceDistributionBase,
    LogisticDistributionBase,
    LognormDistributionBase,
    NormDistributionBase,
    PoissonDistributionBase,
    ScipyFallbackDistribution,
    TDistributionBase,
    UniformDistributionBase,
    WeibullMinDistributionBase,
    # Backward-compatible aliases
    BetaDistributionBase as BetaDistributionGPU,
    BinomDistributionBase as BinomDistributionGPU,
    CauchyDistributionBase as CauchyDistributionGPU,
    Chi2DistributionBase as Chi2DistributionGPU,
    ExponDistributionBase as ExponDistributionGPU,
    FDistributionBase as FDistributionGPU,
    GammaDistributionBase as GammaDistributionGPU,
    LaplaceDistributionBase as LaplaceDistributionGPU,
    LogisticDistributionBase as LogisticDistributionGPU,
    LognormDistributionBase as LognormDistributionGPU,
    NormDistributionBase as NormDistributionGPU,
    PoissonDistributionBase as PoissonDistributionGPU,
    TDistributionBase as TDistributionGPU,
    UniformDistributionBase as UniformDistributionGPU,
    WeibullMinDistributionBase as WeibullMinDistributionGPU,
    beta,
    binom,
    cauchy,
    chi2,
    expon,
    f,
    gamma,
    get_distribution,
    get_distribution_gpu,
    laplace,
    list_available_distributions,
    list_available_distributions_gpu,
    logistic,
    lognorm,
    norm,
    poisson,
    t,
    uniform,
    weibull_min,
)
from ._distributions_legacy_gpu import (
    dbeta_gpu,
    dbinom_gpu,
    dchisq_gpu,
    df_gpu,
    dgamma_gpu,
    dnorm_gpu,
    dpois_gpu,
    dt_gpu,
    norm_cdf_gpu,
    norm_isf_gpu,
    norm_ppf_gpu,
    norm_sf_gpu,
    norm_two_sided_critical_value_gpu,
    norm_two_sided_pvalue_gpu,
    pbeta_gpu,
    pbinom_gpu,
    pchisq_gpu,
    pf_gpu,
    pgamma_gpu,
    pnorm_gpu,
    ppois_gpu,
    pt_gpu,
    qbeta_gpu,
    qbinom_gpu,
    qchisq_gpu,
    qf_gpu,
    qgamma_gpu,
    qnorm_gpu,
    qpois_gpu,
    qt_gpu,
    rbeta_gpu,
    rbinom_gpu,
    rchisq_gpu,
    rf_gpu,
    rgamma_gpu,
    rnorm_gpu,
    rpois_gpu,
    rt_gpu,
    t_cdf_gpu,
    t_ppf_gpu,
    t_sf_gpu,
    t_two_sided_critical_value_gpu,
    t_two_sided_pvalue_gpu,
)
from ._multiple_testing import adjust_pvalues, combine_pvalues, multipletests
from ._resampling import (
    BootstrapResult,
    PermutationTestResult,
    bootstrap_statistic,
    permutation_test,
)
from statgpu.nonparametric._kde import (
    KDE,
    KDEBootstrapResult,
    fit_kde,
    kde_pdf,
    kde_bootstrap_confidence_interval,
)

__all__ = [
    "adjust_pvalues",
    "combine_pvalues",
    "multipletests",
    # Distribution base classes
    "NormDistributionBase",
    "TDistributionBase",
    "UniformDistributionBase",
    "ExponDistributionBase",
    "CauchyDistributionBase",
    "LaplaceDistributionBase",
    "LogisticDistributionBase",
    "Chi2DistributionBase",
    "GammaDistributionBase",
    "BetaDistributionBase",
    "FDistributionBase",
    "WeibullMinDistributionBase",
    "LognormDistributionBase",
    "PoissonDistributionBase",
    "BinomDistributionBase",
    "ScipyFallbackDistribution",
    # Factory
    "get_distribution",
    "get_distribution_gpu",
    "list_available_distributions",
    "list_available_distributions_gpu",
    # Module-level proxies
    "norm", "t", "uniform", "expon", "cauchy", "laplace",
    "logistic", "chi2", "gamma", "beta", "f",
    "weibull_min", "lognorm", "poisson", "binom",
    # Legacy GPU names (backward compat)
    "NormDistributionGPU",
    "TDistributionGPU",
    "UniformDistributionGPU",
    "ExponDistributionGPU",
    "CauchyDistributionGPU",
    "LaplaceDistributionGPU",
    "LogisticDistributionGPU",
    "Chi2DistributionGPU",
    "GammaDistributionGPU",
    "BetaDistributionGPU",
    "FDistributionGPU",
    "WeibullMinDistributionGPU",
    "LognormDistributionGPU",
    "PoissonDistributionGPU",
    "BinomDistributionGPU",
    # Legacy function names
    "norm_cdf_gpu",
    "norm_isf_gpu",
    "norm_ppf_gpu",
    "norm_sf_gpu",
    "norm_two_sided_critical_value_gpu",
    "norm_two_sided_pvalue_gpu",
    "t_cdf_gpu",
    "t_ppf_gpu",
    "t_sf_gpu",
    "t_two_sided_critical_value_gpu",
    "t_two_sided_pvalue_gpu",
    "dnorm_gpu",
    "pnorm_gpu",
    "qnorm_gpu",
    "rnorm_gpu",
    "dt_gpu",
    "pt_gpu",
    "qt_gpu",
    "rt_gpu",
    "dchisq_gpu",
    "pchisq_gpu",
    "qchisq_gpu",
    "rchisq_gpu",
    "dgamma_gpu",
    "pgamma_gpu",
    "qgamma_gpu",
    "rgamma_gpu",
    "dbeta_gpu",
    "pbeta_gpu",
    "qbeta_gpu",
    "rbeta_gpu",
    "df_gpu",
    "pf_gpu",
    "qf_gpu",
    "rf_gpu",
    "dpois_gpu",
    "ppois_gpu",
    "qpois_gpu",
    "rpois_gpu",
    "dbinom_gpu",
    "pbinom_gpu",
    "qbinom_gpu",
    "rbinom_gpu",
    # Resampling
    "BootstrapResult",
    "PermutationTestResult",
    "bootstrap_statistic",
    "permutation_test",
    # KDE
    "KDE",
    "KDEBootstrapResult",
    "fit_kde",
    "kde_pdf",
    "kde_bootstrap_confidence_interval",
]
